// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0HecSgDyJv0_fV5gVly2dERLmI4rpXB8',
    appId: '1:274980396110:web:59f29f183074131b52771f',
    messagingSenderId: '274980396110',
    projectId: 'inclass-test-9edf4',
    authDomain: 'inclass-test-9edf4.firebaseapp.com',
    storageBucket: 'inclass-test-9edf4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCixle8kyiohNprMmIA10lzaR8hOpI0tw',
    appId: '1:274980396110:android:51ccca62ebee179852771f',
    messagingSenderId: '274980396110',
    projectId: 'inclass-test-9edf4',
    storageBucket: 'inclass-test-9edf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcj8V2iKL_TDEZs3ASp8ZuXAXb1synmls',
    appId: '1:274980396110:ios:42e0bc9cbcb1171952771f',
    messagingSenderId: '274980396110',
    projectId: 'inclass-test-9edf4',
    storageBucket: 'inclass-test-9edf4.appspot.com',
    iosBundleId: 'com.example.inclassTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcj8V2iKL_TDEZs3ASp8ZuXAXb1synmls',
    appId: '1:274980396110:ios:a28ae3077d3412a952771f',
    messagingSenderId: '274980396110',
    projectId: 'inclass-test-9edf4',
    storageBucket: 'inclass-test-9edf4.appspot.com',
    iosBundleId: 'com.example.inclassTest.RunnerTests',
  );
}
